version: '2.9'


services:

  alert:
    hostname: alert
    container_name: alert-bot-service
    image: alert:latest
    build:
      context: .
      dockerfile: alert/Dockerfile
      args:
        version: ${VERSION}
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      PRODUCT_SERVICE_URL: http://product:8087
      AUTH_SERVER: http://auth-service:3366
    volumes:
      - ./build/libs/alert-${VERSION}.jar:/alert.jar
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    hostname: mongo
    container_name: hm-mongo
    image: mongo:5.0.5
    restart: on-failure
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo_volume:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
