server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: alert-bot-service

  webflux:
    base-path: /

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:alert}

springdoc:
  swagger-ui:
    path: /swagger-ui.html


info:
  app:
    name: ${spring.application.name}
    version: "@application.version@"
    description: "@application.description@"


application:
  product:
    base-url: ${PRODUCT_SERVICE_URL:http://localhost:8087}
    product-url: ${PRODUCT_URL:http://localhost/product/}
  auth-server:
    base-url: ${AUTH_SERVER:http://localhost:3366}
  telegram-bot:
    token: 6292973353:AAFEWzN4jRWbLbKRwLGa0sYp-zJeZGcdVno
    base-url: ${TELEGRAM_BASE_URL:https://api.telegram.org/bot}
